# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: MockingjayWong的博客
  version: 
  folders:

  - title: 个人相关
    output: web
    folderitems:
    - title: 简介
      url: /introduction.html
      output: web

  - title: 博客分类
    output: web
    folderitems:

    - title: 博客Xmind图记录
      url: /mydoc_tag_archives_overview.html
      output: web

      subfolders:
      - title: Jekyll模板博客实践
        output: web
        subfolderitems:

        - title: Jekyll模板使用错误记录
          url: /jekyll_developing.html
          output: web
